config/routes.rb
Relics::Application.routes.draw do
  match 'combo/cidades/:estado_id' => 'combo#cidades_por_uf'
  match 'combo/cidades/com_loja/:estado_id' => 'combo#cidades_por_uf_com_loja'

  match 'combo/bairros/:cidade_id' => 'combo#bairros_por_cidade'
  match 'combo/bairros/com_loja/:cidade_id' => 'combo#bairros_por_cidade_com_loja'
  
  match 'loja/carregar_dados_templo/:templo_id' => 'lojas#carregar_dados_templo'
  match 'loja/carregar_dados_endereco/:loja_id' => 'lojas#carregar_dados_endereco'
  match 'loja/carregar/:loja_id' => 'irmaos#carregar_loja'
  
  match 'verificar_pessoa/:identificador/em/:loja_id' => 'irmaos#verificar_pessoa'
  match 'irmaos/:identificador/filiar/:loja_id' => 'irmaos#filiar_a_loja'
  match 'irmaos/:identificador/desfiliar/:loja_id' => 'irmaos#desfiliar_de_loja'
  match 'evento/adicionar_foto' => 'eventos#adicionar_foto'
  match 'evento/remover_foto/:id/:evento_id' => 'eventos#remover_foto'

  match 'selecionar_loja/:loja_id' => 'application#selecionar_loja'

  authenticated :user do
    root :to => 'dashboard#index'
  end

  devise_scope :user do
    root :to => "devise/sessions#new", :as => :new_user_session
  end

  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    get "cadastro" => "devise/registrations#new", :as => :new_user
    delete 'sair' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  
  devise_for :users

  resources :users
  resources :irmaos, :as => "pessoas"
  resources :pessoas
  resources :lojas
  resources :ritos
  resources :obediencias
  resources :orientes_estaduais
  resources :dashboard
  resources :permissoes
  resources :dependentes
  resources :eventos
  resources :pecas
  resources :eleicoes, :path => "administracao"
  get 'eleicoes/verificar_irmao/:cim' => 'eleicoes#verificar_irmao'
  
  match 'pecas/:id/texto' => 'pecas#exibir_texto'

  resources :fundadores

  resources :fundadores
  post 'fundadores/adicionar' => 'fundadores#adicionar'
  get 'verificar_irmao/:cim' => 'fundadores#verificar_irmao'
  get 'verificar_fundador_ja_adicionado/:cim' => 'fundadores#verificar_fundador_ja_adicionado'

  put 'update_password' => 'users#update_password'
end

app/models/loja.rb
# coding: utf-8

class Loja < ActiveRecord::Base
  extend Enumerize

  attr_accessible :obediencia_id, :oriente_estadual_id, :nome, :rito_id, :templo_id, :circunscricao, :fundacao, :situacao, :estandarte, :curriculo, :numero, :dia, :hora, :estado_id, :cidade_id, :bairro_id, :endereco, :cep

  delegate :sigla, :to => :obediencia, :prefix => true
  delegate :sigla, :to => :oriente_estadual, :prefix => true
  delegate :nome, :to => :rito, :prefix => true
  delegate :uf, :to => :templo, :prefix => true, :allow_nil => true
  delegate :cidade_nome, :to => :templo, :prefix => true, :allow_nil => true

  belongs_to :obediencia
  belongs_to :oriente_estadual
  belongs_to :rito
  belongs_to :templo
  belongs_to :user
  has_and_belongs_to_many :users
  has_many :irmaos, :class_name => Pessoa
  belongs_to :estado
  belongs_to :cidade
  belongs_to :bairro
  has_many :eventos
  has_and_belongs_to_many :fundadores
  has_many :pecas

  validates_presence_of :obediencia_id, :message => "informe uma obediência"
  validates_presence_of :oriente_estadual_id, :message => "informe um oriente estadual"
  validates_presence_of :nome, :message => "informe um nome"
  validates_presence_of :rito_id, :message => "informe um rito"
  validates :fundacao, :datetime => true

  enumerize :situacao, in: { :ativa => 1, :inativa => 0 }

  has_attached_file :estandarte, :styles => { :medium => "200x200>", :thumb => "100x100>" }, :default_url => "/assets/:style/missing.png"

  validate :validar_tamanho_estandarte
  validate :validar_endereco

  def validar_tamanho_estandarte
    errors.add(:estandarte, "O estandarte deve possuir menos de 400K") if self.estandarte_file_size.present? and self.estandarte_file_size > 400.kilobytes
  end

  def validar_endereco
    if !self.templo.present? and !self.endereco.present? and !self.cep.present? and !self.estado_id.present? and !self.cidade_id.present? and !self.bairro_id.present?
      errors.add(:templo_id, "Informe um templo ou preencha um endereço")
    end
  end

  scope :todas, order("nome ASC")

  def membros
    Filiacao.joins(:pessoa).where("loja_id = ? AND filiado_em <> 'NULL' AND pessoas.data_nascimento <> 'NULL'", self.id).all
  end

  def membros_ids
    Filiacao.joins(:pessoa).where("loja_id = ? AND filiado_em <> 'NULL' AND pessoas.data_nascimento <> 'NULL'", self.id).map(&:pessoa_id)
  end

  def self.do_mesmo_estado(loja)
    if loja.templo.present?
      joins(:templo).where("templos.estado_id = ? AND lojas.fundacao <> 'NULL'", loja.templo.estado.id)
    else
      where("lojas.estado_id = ? AND lojas.fundacao <> 'NULL'", loja.estado.id)
    end
  end

  def possui_templo?
    true if templo.present?
  end
end

app/controllers/lojas_controller.rb
class LojasController < ApplicationController
  layout "interno"

  #load_and_authorize_resource
  before_filter :combos, :only => [:index, :new, :create, :edit, :update]

  def index
    @search = Loja.search(params[:search])
    @ufs = Estado.todos_com_loja.collect { |r| [r.uf, r.id] }
    @lojas = @search.order("nome ASC").paginate(:page => params[:page])
  end

  def new
    @loja = Loja.new
  end

  def create
    @loja = Loja.new(params[:loja])

    if params[:loja][:templo_id].present?
      @loja.endereco = nil
      @loja.bairro_id = nil
      @loja.cidade_id = nil
      @loja.estado_id = nil
      @loja.cep = nil
    else
      @loja.endereco = params[:loja][:endereco]
      @loja.bairro_id = params[:loja][:bairro_id]
      @loja.cidade_id = params[:loja][:cidade_id]
      @loja.estado_id = params[:loja][:estado_id]
      @loja.cep = params[:loja][:cep]
    end

    if @loja.save
      redirect_to :action => :index
    else
      render :action => :new
    end
  end

  def edit
    @loja = Loja.where("id = ?", params[:id]).first
  end

  def update
    @loja = Loja.where("id = ?", params[:id]).first

    if params[:loja][:templo_id].present?
      @loja.endereco = nil
      @loja.bairro_id = nil
      @loja.cidade_id = nil
      @loja.estado_id = nil
      @loja.cep = nil
    else
      @loja.endereco = params[:loja][:endereco]
      @loja.bairro_id = params[:loja][:bairro_id]
      @loja.cidade_id = params[:loja][:cidade_id]
      @loja.estado_id = params[:loja][:estado_id]
      @loja.cep = params[:loja][:cep]
    end

    if @loja.update_attributes(params[:loja])
      redirect_to :action => :index
    else
      render :action => :edit
    end
  end

  def destroy
    @loja = Loja.where("id = ?", params[:id]).first
    @loja.destroy

    redirect_to :action => :index
  end

  def carregar_dados_templo
    @templo = Templo.where("id = ?", params[:templo_id]).first
  end

  def carregar_dados_endereco
    @loja = Loja.where("id = ?", params[:loja_id]).first
  end

  private

  def combos
    @obediencias = Obediencia.todas.collect { |o| [o.sigla, o.id] }  
    @orientes_estaduais = OrienteEstadual.todos.collect { |oe| [oe.sigla, oe.id] }
    @ritos = Rito.todos.collect { |r| [r.nome, r.id] }
    @ufs = Estado.todos.collect { |r| [r.uf, r.id] }
    @templos = Templo.todos.collect { |t| [t.nome, t.id ]}
  end

  def carregar_loja
    @loja = Loja.where("id = ?", session[:loja_id]).first
  end
end

app/views/lojas/administracao.html.erb
<div class="mws-panel grid_6">
	<div class="mws-panel-header">
		<div style="float: right; margin-top: -4px;">

		</div>

		<span>Irmãos da loja <%= @loja.nome %></span>
	</div>

	<div class="mws-panel-body no-padding">
		<div id="DataTables_Table_1_wrapper" class="dataTables_wrapper" role="grid">
			<table class="mws-table">
				<thead>
					<tr>
						<th>Nome</th>
						<th>Ações</th>
					</tr>
				</thead>
				<tbody>
					<% @irmaos_filiados.each do |irmao| %>
						<tr>
							<td><%= irmao.pessoa.nome %></td>
							<td>
								<span><i class="icon-search"></i><span>
								<%= link_to "Consultar", edit_pessoa_path(irmao), :style => "color: black;" %>

								&nbsp;

								<span><i class="icon-tools"></i><span>
								<%= link_to "Cargo", "/loja/administracao/#{irmao.pessoa.id}/cargo", :style => "color: black;" %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>

			<%= page_entries_info(@irmaos_filiados) %>

			<%= will_paginate(@irmaos_filiados, :renderer => WillPaginate::ActionView::RelicsLinkRenderer) %>
		</div>
	</div>
</div>

<div class="mws-panel grid_2">
	<%#= render "lojas/partials/filtro" %>
</div>

app/views/lojas/cargo.html.erb
<div class="mws-panel grid_8">
	<div class="mws-panel-header">
		<span>Administração da loja <%= @loja.nome %></span>
	</div>

	<div class="mws-panel-body no-padding">
		<%#= form_for @eleicao, "/loja/administracao/#{@irmao.id}/adicionar_cargo", :class => "mws-form" do |f| %>
			<%= form_for @eleicao, url: { action: "create" }, :class => "mws-form" do |f| %>
			<% if flash.present? %>
				<div class="mws-form-message error">
					Ocorreu um erro

	        <ul>
	        	<li><%= flash[:notice] %></li>
	        </ul>
				</div>
			<% end %>

			<div class="mws-form-inline">
				<div class="mws-form-row">
					<label class="mws-form-label" style="width: 180px;">
						<strong><%= @irmao.nome %></strong>
					</label>
					<div class="mws-form-item">
						<%= @eleicao.inspect %>
						<%= f.select :cargo_id, @cargos, { :include_blank => "Selecione o cargo" }, { :class => "small" } %>
					</div>
				</div>

				<div class="mws-form-row">
					<label class="mws-form-label" style="width: 180px;">
						Período
					</label>
					<div class="mws-form-item">
						<%= text_field_tag :periodo, nil, maxlength: 10, class: "small" %>
					</div>
				</div>
			</div>

			<div class="mws-button-row">
				<input type="submit" value="Salvar" class="btn btn-success">
				<input type="reset" value="Cancelar" class="btn" onclick="window.location.href='/lojas';">
			</div>
		<% end %>
	</div>    	
</div>

app/views/lojas/carregar_dados_endereco.js.erb
$("#loja_endereco").val("<%= @loja.endereco %>");
$("#estado_id").val("<%= @loja.estado.id %>");

// CIDADE POR ESTADO
$.getJSON("/combo/cidades/<%= @loja.estado.id %>", function(data) {
	$("#bairro_id").empty();
	$("#cidade_id").empty();
	$("<option value=''>Selecione</option>").appendTo("#cidade_id");
	$("<option value=''>Selecione</option>").appendTo("#bairro_id");

	$.each(data, function(i,item) {
		$("<option value=\"" + item.id + "\">" + item.nome + "</option>").appendTo("#cidade_id");
	});
}).done(function() {
	$("#cidade_id").val("<%= @loja.cidade.id %>");

	// BAIRRO POR CIDADE
	$.getJSON("/combo/bairros/<%= @loja.cidade.id %>", function(data) {
		$("#bairro_id").empty();
		$("<option value=''>Selecione</option>").appendTo("#bairro_id");

		$.each(data, function(i,item) {
			$("<option value=\"" + item.id + "\">" + item.nome + "</option>").appendTo("#bairro_id");
		});
	}).done(function() {
		$("#bairro_id").val("<%= @loja.bairro.id %>");
	});
});

$("#loja_cep").val("<%= @loja.cep %>");

app/views/lojas/carregar_dados_templo.js.erb
$("#loja_endereco").val("<%= @templo.endereco %>");
$("#estado_id").val("<%= @templo.estado.id %>");

// CIDADE POR ESTADO
$.getJSON("/combo/cidades/<%= @templo.estado.id %>", function(data) {
	$("#bairro_id").empty();
	$("#cidade_id").empty();
	$("<option value=''>Selecione</option>").appendTo("#cidade_id");
	$("<option value=''>Selecione</option>").appendTo("#bairro_id");

	$.each(data, function(i,item) {
		$("<option value=\"" + item.id + "\">" + item.nome + "</option>").appendTo("#cidade_id");
	});
}).done(function() {
	$("#cidade_id").val("<%= @templo.cidade.id %>");

	// BAIRRO POR CIDADE
	$.getJSON("/combo/bairros/<%= @templo.cidade.id %>", function(data) {
		$("#bairro_id").empty();
		$("<option value=''>Selecione</option>").appendTo("#bairro_id");

		$.each(data, function(i,item) {
			$("<option value=\"" + item.id + "\">" + item.nome + "</option>").appendTo("#bairro_id");
		});
	}).done(function() {
		$("#bairro_id").val("<%= @templo.bairro.id %>");
	});
});

$("#loja_cep").val("<%= @templo.cep %>");

app/views/lojas/edit.html.erb
<%= render "/lojas/partials/form" %>

app/views/lojas/index.html.erb
<div class="mws-panel grid_6">
	<div class="mws-panel-header">
		<div style="float: right; margin-top: -4px;">
			<% if current_user.has_role?(:admin_master) %>
				<%= link_to "Nova loja", "/lojas/new", :class => "btn btn-success" %>
			<% end %>
		</div>

		<span>Lojas</span>
	</div>

	<div class="mws-panel-body no-padding">
		<div id="DataTables_Table_1_wrapper" class="dataTables_wrapper" role="grid">
			<table class="mws-table">
				<thead>
					<tr>
						<th>Obediência</th>
						<th>Oriente Estadual</th>
						<th>Nome</th>
						<th>Rito</th>
						<th>UF</th>
						<th>Cidade</th>
						<th>Ações</th>
					</tr>
				</thead>
				<tbody>
					<% @lojas.each do |loja| %>
						<tr>
							<td><%= loja.obediencia_sigla %></td>
							<td><%= loja.oriente_estadual_sigla %></td>
							<td><%= loja.nome %></td>
							<td><%= loja.rito_nome %></td>

							<% if loja.possui_templo? %>
								<td><%= loja.templo_uf %></td>
								<td><%= loja.templo_cidade_nome %></td>
							<% else %>
								<td><%= loja.estado.uf %></td>
								<td><%= loja.cidade.nome %></td>
							<% end %>
							<td>
								<span><i class="icon-search"></i><span>
								<%= link_to "Consultar", edit_loja_path(loja), :style => "color: black;" %>

								&nbsp;

								<% if can? :excluir, Loja %>
									<span><i class="icon-trash"></i><span>
									<%= link_to "Excluir", loja_path(loja), :method => :delete, :confirm => "Confirma a exclusão ?", :style => "color: black;" %>
								<% end %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>

			<%= page_entries_info(@lojas) %>

			<%= will_paginate(@lojas, :renderer => WillPaginate::ActionView::RelicsLinkRenderer) %>
		</div>
	</div>
</div>

<div class="mws-panel grid_2">
	<%= render "lojas/partials/filtro" %>
</div>

app/views/lojas/new.html.erb
<%= render "/lojas/partials/form" %>