config/routes.rb
Relics::Application.routes.draw do
  match 'combo/cidades/:estado_id' => 'combo#cidades_por_uf'
  match 'combo/cidades/com_loja/:estado_id' => 'combo#cidades_por_uf_com_loja'

  match 'combo/bairros/:cidade_id' => 'combo#bairros_por_cidade'
  match 'combo/bairros/com_loja/:cidade_id' => 'combo#bairros_por_cidade_com_loja'
  
  match 'loja/carregar_dados_templo/:templo_id' => 'lojas#carregar_dados_templo'
  match 'loja/carregar_dados_endereco/:loja_id' => 'lojas#carregar_dados_endereco'
  match 'loja/carregar/:loja_id' => 'irmaos#carregar_loja'
  
  match 'verificar_pessoa/:identificador/em/:loja_id' => 'irmaos#verificar_pessoa'
  match 'irmaos/:identificador/filiar/:loja_id' => 'irmaos#filiar_a_loja'
  match 'irmaos/:identificador/desfiliar/:loja_id' => 'irmaos#desfiliar_de_loja'
  match 'evento/adicionar_foto' => 'eventos#adicionar_foto'
  match 'evento/remover_foto/:id/:evento_id' => 'eventos#remover_foto'

  match 'selecionar_loja/:loja_id' => 'application#selecionar_loja'

  authenticated :user do
    root :to => 'dashboard#index'
  end

  devise_scope :user do
    root :to => "devise/sessions#new", :as => :new_user_session
  end

  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    get "cadastro" => "devise/registrations#new", :as => :new_user
    delete 'sair' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  
  devise_for :users

  resources :users
  resources :irmaos, :as => "pessoas"
  resources :pessoas
  resources :lojas
  resources :ritos
  resources :obediencias
  resources :orientes_estaduais
  resources :dashboard
  resources :permissoes
  resources :dependentes
  resources :eventos
  resources :pecas
  resources :eleicoes, :path => "administracao"
  get 'eleicoes/verificar_irmao/:cim' => 'eleicoes#verificar_irmao'
  
  match 'pecas/:id/texto' => 'pecas#exibir_texto'

  resources :fundadores

  resources :fundadores
  post 'fundadores/adicionar' => 'fundadores#adicionar'
  get 'verificar_irmao/:cim' => 'fundadores#verificar_irmao'
  get 'verificar_fundador_ja_adicionado/:cim' => 'fundadores#verificar_fundador_ja_adicionado'

  put 'update_password' => 'users#update_password'
end

app/models/peca.rb
# coding: utf-8

class Peca < ActiveRecord::Base
  attr_accessible :tema, :grau_id, :autor_id, :autor, :responsavel_id, :texto, :tipo_documento, :autor_nome, :arquivo, :tipo_peca_id, :visibilidade_ids

  TEXTO = 1
  ARQUIVO = 2

  AUTOR_IRMAO = 1
  AUTOR_OUTRO = 2

  VALID_CONTENT_TYPES = ["application/pdf"]

  belongs_to :autor, :class_name => "Pessoa", :foreign_key => "autor_id"
  belongs_to :responsavel, :class_name => "Pessoa", :foreign_key => "responsavel_id"
  belongs_to :categoria, :class_name => "TipoPeca", :foreign_key => "tipo_peca_id"
  belongs_to :criador, :class_name => "Pessoa", :foreign_key => "pessoa_id"
  belongs_to :grau
  has_and_belongs_to_many :visibilidades

  has_attached_file :arquivo

  validates_presence_of :tema, :grau_id, :tipo_peca_id, :responsavel_id
  validates_presence_of :visibilidades, :message => "Selecione a visibilidade"
  validates_length_of :tema, :maximum => 100
  validate :attachment_content_type
  validate :autoria
  validate :documento

  def attachment_content_type
    if self.arquivo_file_name.present?
      if !VALID_CONTENT_TYPES.include?(self.arquivo_content_type)
        errors.add(:arquivo, "Somente arquivos PDF são aceitos")
      end
    end
  end

  def documento
    if self.texto.blank? and self.arquivo_file_name.nil?
      errors.add(:texto, "Informe o texto ou documento")
    end
  end

  def autoria
    if self.autor.nil? and self.autor_nome.blank?
      errors.add(:autor_id, "Informe um autor")
    end
  end
end

app/controllers/pecas_controller.rb
class PecasController < ApplicationController
  layout "interno"

  before_filter :carregar_loja, :only => [:index, :new, :create, :edit, :update]
  before_filter :combos, :only => [:new, :index, :create, :edit, :update]

  def index
    if params[:grau_id].present?
      search = { "grau_id_less_than_or_equal_to" => params[:grau_id] }.merge(params[:search] || {})
    else
      if current_user.has_role?(:admin_master)
        search = { "grau_id_less_than_or_equal_to" => Grau::GRAU_MAXIMO }.merge(params[:search] || {})
      else
        search = { "grau_id_less_than_or_equal_to" => current_user.pessoa.grau.id }.merge(params[:search] || {})
      end
    end

    @search = Peca.search(search)
    @pecas = @search.where("loja_id = ?", @loja.id).order("created_at DESC").paginate(:page => params[:page])
  end

  def new
    @peca = Peca.new
  end

  def create
    @peca = Peca.new(params[:peca])
    @peca.criador = current_user.pessoa

    if @peca.save
      @loja.pecas << @peca

      redirect_to :action => :index
    else
      render :action => :new
    end
  end

  def edit
    @peca = Peca.where("id = ?", params[:id]).first
  end

  def update
    @peca = Peca.where("id = ?", params[:id]).first

    if params[:peca][:visibilidade_ids].nil?
      @peca.visibilidades = []
    end

    if @peca.update_attributes(params[:peca])
      @peca.criador = current_user.pessoa

      if @peca.tipo_documento == 1
        @peca.arquivo = nil
      elsif @peca.tipo_documento == 2
        @peca.texto = nil
      end

      @peca.save

      redirect_to :action => :index
    else
      render :action => :edit
    end
  end

  def destroy
    @peca = Peca.where("id = ?", params[:id]).first
    @peca.destroy

    redirect_to :action => :index
  end

  def exibir_texto
    @peca = Peca.where("id = ?", params[:id]).first
  end

  private

  def carregar_loja
    @loja = Loja.where("id = ?", session[:loja_id]).first
  end

  def combos
    if current_user.has_role?(:admin_master)
      @graus = Grau.todos.collect { |grau| [grau.nome, grau.id] }
    else
      @graus = Grau.hierarquia(current_user).collect { |grau| [grau.nome, grau.id] }
    end

    @autores = @loja.membros.collect { |membro| [membro.pessoa.nome, membro.pessoa.id] }
    @responsaveis = @loja.membros.collect { |membro| [membro.pessoa.nome, membro.pessoa.id] }
    @tipos_pecas = TipoPeca.todos.collect { |tipo| [tipo.nome, tipo.id] }
  end
end

app/views/pecas/edit.html.erb
<%= render "/pecas/partials/form" %>

app/views/pecas/exibir_texto.html.erb
<div class="mws-panel grid_8">
	<div class="mws-panel-header">
		<span><%= @peca.tema %></span>
	</div>
	<div class="mws-panel-body" style="background-color: white;">
		<%= raw @peca.texto %>

		<br />

		<b>Autor: </b> <%= raw @peca.autor.nome %>

		<br /><br />
		<a href="javascript:void(0);" onclick="window.print();" style="color: black;"><i class="icon-print"></i> Imprimir</a>
	</div>
</div>

app/views/pecas/index.html.erb
<div class="mws-panel grid_6">
	<div class="mws-panel-header">
		<div style="float: right; margin-top: -4px;">
			<%= link_to "Nova Peça", "/pecas/new", :class => "btn btn-success" %>
		</div>

		<span>Peças de Arquitetura</span>
	</div>

	<div class="mws-panel-body no-padding">
		<div id="DataTables_Table_1_wrapper" class="dataTables_wrapper" role="grid">
			<table class="mws-table">
				<thead>
					<tr>
						<th>Tema</th>
						<th>Grau</th>
						<th>Categoria</th>
						<th>Responsável</th>
						<th>Documento</th>
						<th>Ações</th>
					</tr>
				</thead>
				<tbody>
					<% @pecas.each do |peca| %>
					<tr>
						<td><%= truncate(peca.tema, length: 50) %></td>
						<td><%= peca.grau %></td>
						<td><%= peca.categoria %></td>
						<td><%= peca.responsavel.try(:nome) %></td>
						<td style="text-align: center;">
							<% unless peca.arquivo_file_name.nil? %>
								<%= link_to "Exibir", peca.arquivo.url, target: "blank" %>
							<% end %>

							<% if peca.texto.present? %>
								<%= link_to "Exibir", "/pecas/#{peca.id}/texto" %>
							<% end %>
						</td>
						<td>
							<span><i class="icon-search"></i><span>
							<%= link_to "Consultar", edit_peca_path(peca), :style => "color: black;" %>

							<% if can? :excluir_peca, @loja or current_user.pessoa.criou_a_peca?(peca.criador) %>
								&nbsp;
								<span><i class="icon-trash"></i><span>
								<%= link_to "Excluir", peca_path(peca), :method => :delete, :confirm => "Confirma a exclusão ?", :style => "color: black;" %>
							<% end %>	
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>

			<%= page_entries_info(@pecas) %>

			<%= will_paginate(@pecas, :renderer => WillPaginate::ActionView::RelicsLinkRenderer) %>
		</div>
	</div>
</div>

<div class="mws-panel grid_2">
	<%= render "pecas/partials/filtro" %>
</div>

app/views/pecas/new.html.erb
<%= render "/pecas/partials/form" %>