config/routes.rb
Relics::Application.routes.draw do
  match 'combo/cidades/:estado_id' => 'combo#cidades_por_uf'
  match 'combo/cidades/com_loja/:estado_id' => 'combo#cidades_por_uf_com_loja'

  match 'combo/bairros/:cidade_id' => 'combo#bairros_por_cidade'
  match 'combo/bairros/com_loja/:cidade_id' => 'combo#bairros_por_cidade_com_loja'
  
  match 'loja/carregar_dados_templo/:templo_id' => 'lojas#carregar_dados_templo'
  match 'loja/carregar_dados_endereco/:loja_id' => 'lojas#carregar_dados_endereco'
  match 'loja/carregar/:loja_id' => 'irmaos#carregar_loja'
  
  match 'verificar_pessoa/:identificador/em/:loja_id' => 'irmaos#verificar_pessoa'
  match 'irmaos/:identificador/filiar/:loja_id' => 'irmaos#filiar_a_loja'
  match 'irmaos/:identificador/desfiliar/:loja_id' => 'irmaos#desfiliar_de_loja'
  match 'evento/adicionar_foto' => 'eventos#adicionar_foto'
  match 'evento/remover_foto/:id/:evento_id' => 'eventos#remover_foto'

  match 'selecionar_loja/:loja_id' => 'application#selecionar_loja'

  authenticated :user do
    root :to => 'dashboard#index'
  end

  devise_scope :user do
    root :to => "devise/sessions#new", :as => :new_user_session
  end

  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    get "cadastro" => "devise/registrations#new", :as => :new_user
    delete 'sair' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  
  devise_for :users

  resources :users
  resources :irmaos, :as => "pessoas"
  resources :pessoas
  resources :lojas
  resources :ritos
  resources :obediencias
  resources :orientes_estaduais
  resources :dashboard
  resources :permissoes
  resources :dependentes
  resources :eventos
  resources :pecas
  resources :eleicoes, :path => "administracao"
  get 'eleicoes/verificar_irmao/:cim' => 'eleicoes#verificar_irmao'
  
  match 'pecas/:id/texto' => 'pecas#exibir_texto'

  resources :fundadores

  resources :fundadores
  post 'fundadores/adicionar' => 'fundadores#adicionar'
  get 'verificar_irmao/:cim' => 'fundadores#verificar_irmao'
  get 'verificar_fundador_ja_adicionado/:cim' => 'fundadores#verificar_fundador_ja_adicionado'

  put 'update_password' => 'users#update_password'
end

app/controllers/fundadores_controller.rb
# coding: utf-8

class FundadoresController < ApplicationController
  layout "interno"

  before_filter :carregar_loja, :only => [:index, :new, :create, :destroy]

  def new
    @fundador = Fundador.new
  end

  def index
    @search = Fundador.search(params[:search])
    @fundadores = @loja.fundadores.order("nome ASC").search(params[:search]).paginate(:page => params[:page])
  end

  def create
    @fundador = Fundador.where("cim = ?", params[:fundador][:cim]).first

    if verificar_fundador_ja_adicionado(params[:fundador][:cim])
      flash[:notice] = "Fundador já adicionado ao quadro de fundadores da loja"
      redirect_to action: :new
      return
    end

    # cria irmao
    if params[:nome].present? and params[:email].present?
     criar_irmao_usuario_e_fundador(params)
    end

    if @fundador.present?
      @loja.fundadores << @fundador

      redirect_to action: :index
    end
  end

  def criar_irmao_usuario_e_fundador(params)
    # irmao
    irmao = Fundador.new
    irmao.cim = params[:fundador][:cim]
    irmao.nome = params[:nome]
    irmao.email_particular = params[:email]
    irmao.categoria = Categoria::IRMAO

    if irmao.save(validate: false)
      irmao.filiar_a_loja(@loja)

      # usuario
      user = User.create!(:email => params[:email], :password => "123456", :password_confirmation => "123456", :confirmed_at => Time.now)
      user.roles << Role::USUARIO

      irmao.user_id = user.id
      irmao.save(validate: false)

      # fundador
      @loja.fundadores << irmao

      redirect_to action: :index
    end
  end

  def verificar_irmao
    existe = Fundador.where("cim = ?", params[:cim]).exists?

    render json: { :irmao_existe => existe }
  end

  def verificar_fundador_ja_adicionado(cim)
    existe = false

    @loja.fundadores.each do |fundador|
      existe = true if fundador.cim == cim
    end

    existe
  end

  def destroy
    fundador = Fundador.where("id = ?", params[:id]).first

    if @loja.fundadores.size > 0 and fundador.present?
      @loja.fundadores.delete(fundador)
    end

    redirect_to :action => :index
  end

  private

  def carregar_loja
    @loja = Loja.where("id = ?", session[:loja_id]).first
  end
end

app/helpers/fundadores_helper.rb
module FundadoresHelper
end

app/views/fundadores/index.html.erb
<div class="mws-panel grid_6">
	<div class="mws-panel-header">
		<div style="float: right; margin-top: -4px;">
			<% if can? :adicionar_fundador, @loja %>
				<%= link_to "Adicionar fundador", new_fundador_path, :class => "btn btn-success" %>
			<% end %>
		</div>

		<span>Quadro de irmãos fundadores da loja <%= @loja.nome %></span>
	</div>

	<div class="mws-panel-body no-padding">
		<div id="DataTables_Table_1_wrapper" class="dataTables_wrapper" role="grid">
			<table class="mws-table">
				<thead>
					<tr>
						<th>Nome</th>
						<th>Ações</th>
					</tr>
				</thead>
				<tbody>
					<% @fundadores.each do |fundador| %>
						<tr>
							<td style="text-align: center;"><%= fundador.nome %></td>
							<td style="text-align: center;">
								<%= link_to "Consultar", edit_pessoa_path(fundador), :style => "color: black;" %>
								&nbsp;
								<% if can? :excluir_fundador, @loja %>
									<span><i class="icon-trash"></i><span>
									<%= link_to "Excluir", fundador_path(fundador), :method => :delete, :confirm => "Confirma a exclusão ?", :style => "color: black;" %>
								<% end %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>

			<%= page_entries_info(@fundadores) %>

			<%= will_paginate(@fundadores, :renderer => WillPaginate::ActionView::RelicsLinkRenderer) %>
		</div>
	</div>
</div>

<div class="mws-panel grid_2">
	<%= render "fundadores/partials/filtro" %>
</div>

app/views/fundadores/irmao_nao_cadastrado.js.erb
alert("aaa");

app/views/fundadores/new.html.erb
<%= render "/fundadores/partials/form" %>