config/routes.rb
Relics::Application.routes.draw do
  match 'combo/cidades/:estado_id' => 'combo#cidades_por_uf'
  match 'combo/cidades/com_loja/:estado_id' => 'combo#cidades_por_uf_com_loja'

  match 'combo/bairros/:cidade_id' => 'combo#bairros_por_cidade'
  match 'combo/bairros/com_loja/:cidade_id' => 'combo#bairros_por_cidade_com_loja'
  
  match 'loja/carregar_dados_templo/:templo_id' => 'lojas#carregar_dados_templo'
  match 'loja/carregar_dados_endereco/:loja_id' => 'lojas#carregar_dados_endereco'
  match 'loja/carregar/:loja_id' => 'irmaos#carregar_loja'
  
  match 'verificar_pessoa/:identificador/em/:loja_id' => 'irmaos#verificar_pessoa'
  match 'irmaos/:identificador/filiar/:loja_id' => 'irmaos#filiar_a_loja'
  match 'irmaos/:identificador/desfiliar/:loja_id' => 'irmaos#desfiliar_de_loja'
  match 'evento/adicionar_foto' => 'eventos#adicionar_foto'
  match 'evento/remover_foto/:id/:evento_id' => 'eventos#remover_foto'

  match 'selecionar_loja/:loja_id' => 'application#selecionar_loja'

  authenticated :user do
    root :to => 'dashboard#index'
  end

  devise_scope :user do
    root :to => "devise/sessions#new", :as => :new_user_session
  end

  as :user do
    get 'login' => 'devise/sessions#new', :as => :new_user_session
    get "cadastro" => "devise/registrations#new", :as => :new_user
    delete 'sair' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  
  devise_for :users

  resources :users
  resources :irmaos, :as => "pessoas"
  resources :pessoas
  resources :lojas
  resources :ritos
  resources :obediencias
  resources :orientes_estaduais
  resources :dashboard
  resources :permissoes
  resources :dependentes
  resources :eventos
  resources :pecas
  resources :eleicoes, :path => "administracao"
  get 'eleicoes/verificar_irmao/:cim' => 'eleicoes#verificar_irmao'
  
  match 'pecas/:id/texto' => 'pecas#exibir_texto'

  resources :fundadores

  resources :fundadores
  post 'fundadores/adicionar' => 'fundadores#adicionar'
  get 'verificar_irmao/:cim' => 'fundadores#verificar_irmao'
  get 'verificar_fundador_ja_adicionado/:cim' => 'fundadores#verificar_fundador_ja_adicionado'

  put 'update_password' => 'users#update_password'
end

app/controllers/permissoes_controller.rb
class PermissoesController < ApplicationController
  layout "interno"

  before_filter :carregar_loja, :only => [:index, :show, :update]

  def index
    @search = Filiacao.search(params[:search])
    @irmaos_filiados = @search.where("loja_id = ?", @loja.id).filiados.joins(:loja, :pessoa).order("pessoas.nome ASC").paginate(:page => params[:page])
  end
 
  def show
    @irmao = Pessoa.where("id = ?", params[:id]).first
    @user = @irmao.user
  end

  def update
    @user = User.find(params[:id])

    if params[:user][:role_ids].to_i == Role::ADMIN_LOJA
      @user.lojas << @loja
    else
      @user.lojas.delete(@loja)
    end

    if @user.update_attributes(params[:user])
      redirect_to :action => :index
    end
  end

  private

  def carregar_loja
    @loja = Loja.where("id = ?", session[:loja_id]).first
  end
end

app/views/permissoes/partials/_filtro.html.erb
<div class="mws-panel-header">
	<span><i class="icon-filter"></i> Filtro</span>
</div>

<div class="mws-panel-body no-padding">
	<%= form_for @search, :url => permissoes_path, :html => { :method => :get, :class => "mws-form" } do |f| %>
		<div class="mws-form-block">
			<div class="mws-form-row bordered">
				<label class="mws-form-label">Nome</label>
				<div class="mws-form-item">
					<%= f.text_field :pessoa_nome_contains, :class => "large" %>
				</div>
			</div>

			<div class="mws-button-row">
				<input type="submit" value="Filtrar" class="btn btn-success">
				<input type="reset" value="Limpar" class="btn " onclick="window.location.href='/permissoes';">
			</div>
		</div>
	<% end %>
</div>

app/views/permissoes/partials/_roles.html.erb
<div class="mws-panel grid_8">
	<div class="mws-panel-header">
		<span>Permissão na loja: &nbsp; <%= @loja.nome %></span>
	</div>

	<div class="mws-panel-body no-padding">
		<%= form_for @user, :url => "/permissoes/#{@user.id}", :html => {:method => :put, :class => 'mws-form' } do |f| %>
			<div class="mws-form-inline">
				<div class="mws-form-row">
					<label class="mws-form-label">
						Nome
					</label>
					<div class="mws-form-item">
						<%= @user.pessoa.nome %>
					</div>
				</div>

				<div class="mws-form-row">
					<label class="mws-form-label">
						E-mail
					</label>
					<div class="mws-form-item">
						<%= @user.pessoa.email_particular %>
					</div>
				</div>

				<div class="mws-form-row">
					<label class="mws-form-label">Perfil</label>
					<div class="mws-form-item">
						<ul class="mws-form-list">
							<% Role.todas.each do |role| %>
								<li>
									<input id="permissao" type="radio" name="user[role_ids]" value="<%= role.id %>" <% if @user.role_ids.include?(role.id) %> checked="checked" <% end %>>
									<label for="permissao"><%= role.name.titleize %></label>
								</li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>

			<div class="mws-button-row">
				<input type="submit" value="Salvar" class="btn btn-success">
				<input type="reset" value="Cancelar" class="btn" onclick="window.location.href='/permissoes';">
			</div>
		<% end %>
	</div>    	
</div>